== Basic Concepts

API Framework is less framework and more development pattern. Where majority of
development patterns are already implemented as part of framework. And any
new functionality can easily be added following exiting patterns.

=== How framework is structured ?
API Framework has clean separation between _Code_ and _Configuration_. In fact
not only configuration, but, class dependencies itself is also configurable. This is major
problem with Vertx implementation. API Framework uses IoC (Inversion of Control)
concept (same as Spring) to achieve its goal.

Once you have configuration separate from Code, next challenge is management of
configuration itself.  How do you make sure that thousands of component configuration
is managed in a way where developers and dev ops can manage configuration in
simple and reliable fashion. In API Framework, we use Glue to manage configuration
in simple *properties* file.

API Framework has its own configuration layer and our project has its own
configuration layer. In our configuration layer, we can override any API Framework
configuration. Any number of layers can be added to API Framework, and
each layer can override configuration of all previous layers (For example, during unit
testing we add test layer containing any specific configuration required for testing).
